[package]
name = "gb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/hidden.rs"

[dependencies]
anyhow = "1.0.68"
atty = "0.2.14"
clap = "4.1.4"
csv = "1.1.6"
dashmap = "5.4.0"
thiserror = "1.0.38"

